name: Terraform Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Copy vnet-subnet into artifact staging directory
        run: |
          mkdir -p ${{ github.workspace }}/artifact_staging/vnet-subnet
          cp -r vnet-subnet/. ${{ github.workspace }}/artifact_staging/vnet-subnet

      - name: Upload terraform artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform
          path: artifact_staging
